name: Build

on:
  push:
    branches-ignore:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        id: docker_build
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          push: false
